// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a5cb482c-d6a0-4788-ab4e-90209d6bd475";
const char SSID[]               = "FASTWEB-M4TDm4-2.4GHZ";    // Network SSID (name)
const char PASS[]               = "6j6dP38v22";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "S7FXNBGKAOSCIVDOJASW";    // Secret device password

void onLedSwitchChange();

int random_value;
bool led_switch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(random_value, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
